/**
 * Created by rasulniyazimbetov on 21/04/16.
 */
var assert = require('chai').assert;
//var Commission = new require('../src/templateModels/commission');
var Classes = require('../src/templateModels');

describe('ESTATE CLASS', () => {
    var Estate = Classes.Estate.getBaseClass();

    it('shall test basic of estate class', function(done) {
        var estate = new Estate(testEstate);

        assert.equal(estate.apartmentInfo, 'hello world');
        done();
    });
});

var testEstate = {
    "id": "MDAwMnwwMDAwMDAwMDAwMXw2Nw..",
    "dealId": "MDAwMnwwMDAwMDAwMDAwMXw1OA..",
    "mainImageFileId": "MDAwMnwwMDAwMDAwMDAwMXw5Ng..",
    "tenureTypeId": null,
    "apartmentNumber": null,
    "governmentApartmentNumber": null,
    "housingAssociationId": "MDAwMnwwMDAwMDAwMDAwNnwxMjU.",
    "housingAssociationBuildingId": null,
    "housingAssociationName": "stockholm asos",
    "housingAssociationFoundedYear": 1988,
    "buildingArea": 80,
    "totalLivingArea": null,
    "plotAreaComment": null,
    "note": null,
    "costAccuracy": null,
    "totalArea": null,
    "propertyDesignation": null,
    "propertyName": "wow house",
    "identifier": null,
    "countryId": null,
    "objectTypeId": "MDAtMXwwMDAwMDAwMDAwMnwzOA..",
    "objectSubTypeId": "MDAtMXwwMDAwMDAwMDAwMXwzOQ..",
    "numberOfRoom": 1,
    "roomsDescription": null,
    "numberOfBedrooms": null,
    "convertNumberOfBedRooms": null,
    "livingArea": 50,
    "livingAreaIsApproximate": false,
    "otherLivingArea": 100,
    "livingAreaComment": null,
    "isLeasehold": false,
    "isPartOf": false,
    "isAcquisitionPermitNeeded": false,
    "isPropertyAssociation": false,
    "plotArea": null,
    "waterArea": null,
    "district": null,
    "streetAddress": "bandolsvegan",
    "postalCode": "10067",
    "city": "Uppsala",
    "isTenureHouse": false,
    "tenureHouseCost": null,
    "tenureHousePeriod": null,
    "tenureHouseLandLord": null,
    "tenureHouseEndDate": null,
    "feeDescription": null,
    "premiseType": null,
    "premiseNumber": null,
    "premiseTenantContractNumber": null,
    "moduleArea": null,
    "premiseTypeText": null,
    "floorPlanDescription": null,
    "localServicesDescription": null,
    "businessDescription": null,
    "displayPremiseRentAs": null,
    "premiseIndex": null,
    "premiseEconomyValuesIsInVAT": false,
    "premiseEconomyValuesVATSetting": null,
    "premiseHideRentOnMarketingPlaces": false,
    "premiseHideRentInObjectDescription": false,
    "businessTradeType": null,
    "businessEquipment": null,
    "businessEstablishedYear": null,
    "businessNumberOfEmployees": null,
    "businessNumberOfCustomers": null,
    "businessRevenue": null,
    "businessProfit": null,
    "renovateYear": null,
    "renovateDescription": null,
    "upcomingRenovationsDescription": null,
    "heatingType": null,
    "heatingPlantCondition": null,
    "heatingPlantAge": null,
    "heatingPlantBrand": null,
    "heatingComment": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    "electricalStemsCondition": null,
    "mainFuse": "16 A ggf",
    "electricalComment": null,
    "standardPoints": null,
    "internetSummary": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    "electricSafety": null,
    "subFoundationType": "Moraine",
    "foundationWallType": null,
    "foundationType": null,
    "frameType": null,
    "joistType": null,
    "facadeType": null,
    "roofingType": "Eternit",
    "guttersType": null,
    "windowsType": null,
    "ventilationType": null,
    "ventilationInspectionDate": null,
    "chimneyType": null,
    "chimneyLastUsedDate": null,
    "chimneyTestDate": null,
    "chimneyComment": null,
    "waterType": null,
    "drainType": null,
    "hasRadon": false,
    "radonComment": null,
    "otherBuildings": null,
    "isAllYear": false,
    "createdDate": "2014-06-03T09:00:01.000Z",
    "costDescription": null,
    "latitude": "59.368608828637406",
    "longitude": "18.006515353918076",
    "zoomLevel": null,
    "directions": null,
    "communications": null,
    "locationComment": null,
    "description": null,
    "floorNr": null,
    "floorsInTotal": null,
    "floorNrComment": null,
    "tenantOwnershipLandComment": null,
    "hasDoorCode": false,
    "doorCode": null,
    "hasKey": false,
    "keyComment": null,
    "keyInDate": null,
    "keyInPersonName": null,
    "keyOutDate": null,
    "keyOutPersonName": null,
    "hasBurglarAlarm": false,
    "burglarAlarmType": null,
    "burglarAlarmCode": null,
    "burglarAlarmComment": null,
    "showBurglarAlarmOnMarketingPlaces": false,
    "hasLiftSetting": null,
    "liftMaxPersons": null,
    "liftMaxLoad": null,
    "liftComment": null,
    "courtyardComment": null,
    "isSatelliteDishAllowed": false,
    "hasCableTv": false,
    "feeChanges": null,
    "cashFlowAnalysisComment": null,
    "cashFlowAnalysisYield": null,
    "plotDescription": null,
    "livingAreaDescription": null,
    "farmingPurposeText": null,
    "patioSummary": null,
    "parkingSummary": null,
    "estateEconomicTypeCodeId": "MDAtMXwwMDAwMDAwMDAwNXwzMw..",
    "assessmentYear": null,
    "assessValueYear": null,
    "assessValueBuilding": 6456,
    "assessValueLand": 54,
    "assessValueTotal": null,
    "assessValueDescription": null,
    "assessmentValueAccuracy": null,
    "yearlyGroundRent": null,
    "groundRentEndDate": null,
    "groundRentPeriod": null,
    "groundRentLandlord": null,
    "monthlyRent": null,
    "isHeatIncluded": false,
    "isWaterIncluded": false,
    "isElectricityIncluded": false,
    "isCableTVIncluded": false,
    "isInternetIncluded": false,
    "isCoolingIncluded": false,
    "isGarageIncluded": false,
    "isCarportIncluded": false,
    "isParkingSpaceIncluded": false,
    "otherFeeIncludedComment": "erwwtertertertregtergherh",
    "livingCostAnalysisComment": null,
    "bboxObjectJSON": null,
    "polygonListJSON": null,
    "monthlyRentSummary": null,
    "transferFee": null,
    "pledgingFee": null,
    "condominiumSupplement": null,
    "repairFund": null,
    "repairFundDescription": null,
    "transferFeePaidBy": "ENUMS_HOUSING_ASSOCIATION_TRANSFER_FEE_PAID_BY_BUYER",
    "pledgingFeePaidBy": "ENUMS_HOUSING_ASSOCIATION_PLEDGING_FEE_PAID_BY_BUYER",
    "repairFundCheckDate": null,
    "isRepairFund": false,
    "shareInCondo": null,
    "shareInCondoContribution": null,
    "isShareInCondo": false,
    "shareInCondoFee": null,
    "isShareInCondoFee": false,
    "shareInCondoComment": null,
    "isPawned": false,
    "isSharedOwnership": false,
    "sharedOwnershipDescription": null,
    "pawnedSetting": null,
    "pawnedAmount": null,
    "pawnedAmountCheckDate": null,
    "pawnedComment": null,
    "heatingCost": null,
    "chimneySweepingCost": null,
    "communityFee": 65754,
    "insuranceFee": 564,
    "insuranceCompany": null,
    "insuranceDescription": null,
    "maintenanceCost": 765,
    "otherOperationCost": null,
    "waterAndDrainFee": 75675,
    "roadFee": 65765,
    "sanitationFee": 65750,
    "householdElectricityCost": null,
    "operationalComment": null,
    "securityCost": null,
    "operatingCostSum": 136548,
    "isOperatingCostSumSetManually": true,
    "energyClass": "ENUMS_ENERGYCLASS_TYPE_C",
    "energyPerformance": 4000,
    "energyDescription": null,
    "energyStatus": "ENUMS_EnergyStatus_TYPE_ENERGY_USE_IN_PROGRESS",
    "energyStatusDate": "2014-10-22T00:00:00.000Z",
    "energyStatusEntrepreneur": null,
    "energyStatusSummary": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    "energyConsumption": null,
    "personsInHousehold": null,
    "buildingComment": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    "otherAreasComment": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    "landComment": "something here",
    "buildingRightsLandDescription": null,
    "mortgageComment": null,
    "loanComment": null,
    "areaComment": null,
    "areaType": null,
    "easementsAndDetailsComment": null,
    "faultsAndDefectsComment": null,
    "residentialArea": null,
    "displayOrder": null,
    "propertyTax": 567464,
    "premiseComment": null,
    "housingComment": null,
    "isRental": false,
    "buildingType": null,
    "kindOfBuilding": null,
    "buildYear": null,
    "tenantsIncomeComment": null,
    "generalInformation": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    "electricityConsumption": null,
    "grantingFee": null,
    "contributionFee": null,
    "keyIdentifier": null,
    "isInternational": false,
    "isExchange": false,
    "cableTvSupplier": null,
    "cableTvCostText": null,
    "isTransferFeePaidBySeller": false,
    "isPledgingFeePaidBySeller": false,
    "convertRoom": null,
    "staircaseTotal": null,
    "patioComment": null,
    "hasLift": false,
    "tenureFee": null,
    "updatedDate": "2016-02-29T15:20:31.000Z",
    deferred: {
        housingAssociation: {
            "id": "MDAwMnwwMDAwMDAwMDAwNnwxMjU.",
            "organizationUnitId": "MDAwMnwwMDAwMDAwMDAwMnw0NA..",
            "name": "stockholm asos",
            "identifier": "gdfg464",
            "taxationType": null,
            "housingAssociationType": "ENUMS_HOUSING_ASSOCIATION_TYPE_PROPERTY_ASSOCIATION",
            "housingAssociationStartDate": null,
            "contactInformationId": "MDAwMnwwMDAwMDAwMDAwN3w3Ng..",
            "foundedYear": 1988,
            "note": null,
            "numberOfApartments": null,
            "numberOfFacilities": null,
            "legalEntityAcceptableSetting": null,
            "transferFee": null,
            "transferFeePaidBy": null,
            "pledgingFeePaidBy": null,
            "generalInformation": null,
            "economy": null,
            "feeChanges": null,
            "ownership": null,
            "upcomingRenovations": null,
            "madeRenovations": null,
            "businessHours": null,
            "errors": null,
            "insurance": null,
            "other": null,
            "pledgingFee": null,
            "otherAreasComment": null,
            "parkingDescription": null,
            "locationDescription": null,
            "directions": null,
            "comment": null,
            "updatedByContactId": null,
            "manuallyUpdatedDate": null,
            "websiteURL": null,
            "communications": null,
            "yearlyRent": null,
            "loans": null,
            "loansPerAreaUnit": null,
            "isLegalEntityOK": false,
            "membershipApplicationSentDate": null,
            "hasLift": false,
            "heatAndAirConditionFacilityComment": null,
            "internetSummary": null,
            "maxFloors": null,
            "buildYear": null,
            "liftComment": null,
            "buildingComment": null,
            "energyClass": null,
            "energyPerformance": null,
            "energyDescription": null,
            "energyStatus": null,
            "energyStatusDate": null,
            "energyStatusEntrepreneur": null,
            "energyStatusSummary": null,
            "updatedDate": "2015-11-09T12:18:56.000Z"
        }
    }
};